# Generated by Django 6.0 on 2025-12-25 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('STRATEGY_GENERATED', 'تم توليد الاستراتيجية (الذكاء الاصطناعي)'), ('AI_NEEDS_INFO', 'الذكاء يحتاج تفاصيل إضافية'), ('FIRST_LEAD', 'أول مشترك (Lead)'), ('READY_TO_LAUNCH', 'المشروع جاهز للإطلاق (40 مشترك)'), ('MILESTONE_REACHED', 'تم تحقيق إنجاز جديد'), ('SYSTEM_ALERT', 'تنبيه نظام'), ('ACCOUNT_SECURITY', 'أمان الحساب')], max_length=50, unique=True, verbose_name='نوع الحدث')),
                ('title_template', models.CharField(max_length=255, verbose_name='قالب العنوان')),
                ('body_template', models.TextField(verbose_name='قالب نص الرسالة')),
                ('send_in_app', models.BooleanField(default=True, verbose_name='إرسال داخل الموقع')),
                ('send_email', models.BooleanField(default=False, verbose_name='إرسال إيميل')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('STRATEGY_GENERATED', 'تم توليد الاستراتيجية (الذكاء الاصطناعي)'), ('AI_NEEDS_INFO', 'الذكاء يحتاج تفاصيل إضافية'), ('FIRST_LEAD', 'أول مشترك (Lead)'), ('READY_TO_LAUNCH', 'المشروع جاهز للإطلاق (40 مشترك)'), ('MILESTONE_REACHED', 'تم تحقيق إنجاز جديد'), ('SYSTEM_ALERT', 'تنبيه نظام'), ('ACCOUNT_SECURITY', 'أمان الحساب')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='bell', max_length=50)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
