# Generated by Django 6.0 on 2025-12-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('STRATEGY_GENERATED', 'تم توليد الاستراتيجية'), ('AI_NEEDS_INFO', 'الذكاء يحتاج تفاصيل إضافية'), ('FIRST_LEAD', 'أول مشترك (Lead)'), ('READY_TO_LAUNCH', 'المشروع جاهز للإطلاق (40 مشترك)'), ('HIGH_POTENTIAL_PROJECT', 'مشروع واعد (للأدمن)'), ('SUSPICIOUS_CONTENT', 'محتوى مشبوه (للأدمن)'), ('SYSTEM_ALERT', 'تنبيه نظام (للأدمن)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('STRATEGY_GENERATED', 'تم توليد الاستراتيجية'), ('AI_NEEDS_INFO', 'الذكاء يحتاج تفاصيل إضافية'), ('FIRST_LEAD', 'أول مشترك (Lead)'), ('READY_TO_LAUNCH', 'المشروع جاهز للإطلاق (40 مشترك)'), ('HIGH_POTENTIAL_PROJECT', 'مشروع واعد (للأدمن)'), ('SUSPICIOUS_CONTENT', 'محتوى مشبوه (للأدمن)'), ('SYSTEM_ALERT', 'تنبيه نظام (للأدمن)')], max_length=50, unique=True, verbose_name='نوع الحدث'),
        ),
    ]
