# Generated by Django 6.0 on 2025-12-23 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incubation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('competitors_data', models.JSONField(blank=True, default=list)),
                ('detected_problems', models.JSONField(blank=True, default=list)),
                ('suggested_sources', models.JSONField(blank=True, default=list)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_report', to='incubation.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('problems_solutions_list', models.JSONField(default=list)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='incubation.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
