# Generated by Django 6.0 on 2025-12-23 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('raw_description', models.TextField()),
                ('target_sector', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('IDEA', 'فكرة جديدة'), ('RESEARCHING', 'جاري البحث'), ('ANALYZED', 'تم التحليل'), ('STRATEGY_SET', 'تم تحديد الحل'), ('LANDING_PAGE', 'صفحة الهبوط جاهزة'), ('PUBLISHED', 'منشور'), ('VALIDATED', 'تم التحقق')], default='IDEA', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
