# Generated by Django 6.0 on 2025-12-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='target_sector',
            field=models.CharField(choices=[('TECH', 'تطبيق / تقنية'), ('FOOD', 'مقهى / مطعم'), ('REAL_ESTATE', 'عقار / مقاولات'), ('GENERAL', 'عام')], default='GENERAL', max_length=50),
        ),
    ]
