# Generated by Django 6.0 on 2025-12-23 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incubation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('main_headline', models.CharField(max_length=255)),
                ('sub_headline', models.TextField(blank=True)),
                ('project_logo', models.ImageField(blank=True, null=True, upload_to='project_logos/')),
                ('features_list', models.JSONField(blank=True, default=list)),
                ('theme_config', models.JSONField(default=dict)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('current_signups', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='incubation.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question_text', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'سؤال نصي'), ('CHOICE', 'اختيار من متعدد'), ('IMAGE_VOTE', 'مقارنة صور (مدفوع)')], default='TEXT', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='questions/ab_test/')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='questions/ab_test/')),
                ('order', models.IntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='launchpad.landingpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('answers_data', models.JSONField(blank=True, default=dict)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='launchpad.landingpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
